apiVersion: v1
kind: Pod
metadata:
  name: my-first-app
  labels:
    app: intro
spec:
  containers:
  - name: busybox
    image: busybox:1.32
    command: ['sh', '-c', 'echo "Hello k8s!" && sleep 3600']

