apiVersion: v1
kind: Pod
metadata:
  name: <your name>
  labels:
    app: intro
spec:
  containers:
  - name: busybox
    image: busybox:1.32
    command: ['sh', '-c', 'echo "Hello <your name>!" && sleep 3600']

