apiVersion: v1
kind: Pod
metadata:
  name: custom-envs-pod
  labels:
    app: env-pod
spec:
  containers:
  - name: busybox
    image: busybox:1.32
    command: ['sh', '-c', 'echo "Hello $NAME, your color is $COLOR" && sleep 3600']
    env:
    - name: NAME
      value: <add your name>
    - name: COLOR
      value: <your color>

